MiniURL/urls.py
from django.urls import path

from MiniURL import views


app_name = "MiniURL"

urlpatterns = [
    path('', views.form_views, name='forms_views'),
    path('redirect/<str:code>', views.redirections, name='redirections')
]

Url_shortener/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

import MiniURL


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('MiniURL.urls'))
]

MiniURL/models.py
from django.db import models

# Create your models here.


class MiniURL(models.Model):
    long_url = models.URLField()
    code = models.CharField(max_length=10, unique=True)
    date_creation = models.DateTimeField(auto_now=False, auto_now_add=True)
    pseudo = models.CharField(max_length=255, blank=True, null=True)
    nbre_access = models.IntegerField(default=0)

    def __str__(self):
        return self.long_url

MiniURL/forms.py
import random
import string

from django import forms


class miniurl_form(forms.Form):
    url = forms.URLField()
    pseudo = forms.CharField(max_length=25, label="Votre pseudo")

MiniURL/views.py
import string
import random

from django.shortcuts import render, get_object_or_404, redirect

# Create your views here.
from MiniURL.models import MiniURL
from MiniURL.forms import miniurl_form


def generate(nb_caracter):
    caracter = string.ascii_letters + string.digits
    randomly = [random.choice(caracter) for _ in range(nb_caracter)]

    return ''.join(randomly)


def form_views(request):
    envoi = False
    list_url = MiniURL.objects.order_by('nbre_access')
    if request.method == 'POST':
        form = miniurl_form(request.POST)
        if form.is_valid():
            url = MiniURL()
            url.code = generate(10)
            url.long_url = form.cleaned_data['url']
            url.pseudo = form.cleaned_data['pseudo']
            url.save()
            envoi = True

        else:
            form = miniurl_form()
    else:
        form = miniurl_form()
    return render(request, 'miniurl_forms.html', {'form': form, 'envoi': envoi, 'list_redirections': list_url})


def redirections(request, code):
    url = get_object_or_404(MiniURL, code=code)
    url.nbre_access += 1
    url.save()

    return redirect(url.long_url, permanent=True, blank=True)

MiniURL/templates/list_url.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Liste URL</title>
</head>

<body>
    <h1>Voici les raccourcis d'urls :</h1>
    <ul>
        {% for url in list_redirections %}
        <li><a href="{{ url.long_url }}">{{ url.long_url }}</a>
            Via
        <a href="{% url 'MiniURL:redirections' url.code %}">{{ url.long_url }}</a>
        par {{ url.pseudo }}
        <a href="{">shortenerURL/{{ url.code }}</a> ({{ url.nbre_access }})</li>
        {% empty %}
        <p>Aucune url n'a encore été définie</p>
        {% endfor %}
    </ul>
</body>
</html>

MiniURL/templates/miniurl_forms.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Racourcisseur URL</title>
</head>
<body>
    <header>
        <nav class="navbar bg-dark mb-3">
            <form action="{% url "MiniURL:forms_views" %}" method="POST" class="container">
                {% csrf_token %}
                <div class="input-group">
                    <span class="input-group-text">URL</span>
                    <input type="text" name="url" title="URL" id="" class="form-control" aria-label="URL" aria-describedby="basic-addon1">
                    <span class="input-group-text">Pseudo</span>
                    <input type="text" class="form-control" aria-label="PSEUDO" aria-labelledby="basic-addon1" name="pseudo">
                    <input type="submit" value="SHORT IT" class="btn btn-success">
                </div>
            </form>
        </nav>
    </header>
    <div class="container">
        <table class="table-dark table">
            <thead class="text-center">
                <tr>
                    <th scope="col">URL long</th>
                    <th scope="col">URL raccourci</th>
                    <th scope="col">Nombre d'accès</th>
                </tr>
            </thead>
            <tbody>
                {% for url in list_redirections %}
                    <tr>
                        <th scope="row"><a href="{% url 'MiniURL:redirections' url.code %}">{{ url.long_url }}</a></th>
                        <td><a href="{% url 'MiniURL:redirections' url.code %}">url.st/{{ url.code }}</a></td>
                        <td>{{ url.nbre_access }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</body>
</html>